name: Notify about new/modified blog posts

on:
  schedule:
    - cron:  '5 6 * * *' # runs every day at 6:05 UTC 
  workflow_dispatch: ~
    
jobs:
  notify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run the script
      run: python new_posts.py
      env:
           WP_BASE_URL:  ${{ secrets.WP_BASE_URL }}
           WP_USER:  ${{ secrets.WP_USER }}
           WP_APPLICATION_PASSWORD:  ${{ secrets.WP_APPLICATION_PASSWORD }}
           MS_TEAMS_WEBHOOK_URL:  ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
